baseURL = 'https://salluthdev.github.io/hugo-demo/'
languageCode = 'en-us'
title = 'Blog | Salluthdev'
theme = 'sl-theme'
summaryLength = 20
paginate = 2
[params]
	Description = "Bantu kamu untuk belajar HTML dan CSS"